import admin from "firebase-admin";

// Initialize Firebase Admin without credentials but with projectId 
// to allow verifying ID tokens generated by the client.
if (!admin.apps.length) {
  admin.initializeApp({
    projectId: "freto-freight",
  });
}

export { admin };
